Q1. What is Min-Max scaling, and how is it used in data preprocessing? Provide an example to illustrate its
application.

In [1]:
#Min-Max Scaling transforms data into a fixed range, usually [0,1] or [-1,1]
#Scaling [10, 20, 30, 40] to [0,1]

from sklearn.preprocessing import MinMaxScaler

data = [[10], [20], [30], [40]]
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(data)
print(scaled_data)



[[0.        ]
 [0.33333333]
 [0.66666667]
 [1.        ]]


Q2. What is the Unit Vector technique in feature scaling, and how does it differ from Min-Max scaling?
Provide an example to illustrate its application.

In [2]:
'''Unit Vector Scaling (Normalization) scales each feature vector to a unit norm


Difference from Min-Max Scaling:
Min-Max Scaling maps values to a fixed range.
Unit Vector Scaling scales values relative to their magnitude.'''


from sklearn.preprocessing import normalize
import numpy as np

data = np.array([[3, 4]])
normalized_data = normalize(data, norm='l2')
print(normalized_data)


[[0.6 0.8]]


Q3. What is PCA (Principle Component Analysis), and how is it used in dimensionality reduction? Provide an
example to illustrate its application.


In [3]:
'''PCA reduces high-dimensional data while preserving maximum variance.


Steps:
Standardize the data.
Compute covariance matrix & eigenvectors.
Select top components with highest variance.'''

from sklearn.decomposition import PCA
import numpy as np

X = np.random.rand(5, 3)  # 5 samples, 3 features
pca = PCA(n_components=2)
X_reduced = pca.fit_transform(X)
print(X_reduced)


[[-0.43677621 -0.10308634]
 [ 0.57163439 -0.08274422]
 [ 0.60211987  0.10543187]
 [-0.32000852 -0.28552751]
 [-0.41696953  0.3659262 ]]


Q4. What is the relationship between PCA and Feature Extraction, and how can PCA be used for Feature
Extraction? Provide an example to illustrate this concept.



In [5]:
'''Feature Extraction creates new, meaningful features from raw data.
PCA extracts principal components as new features.'''


pca = PCA(n_components=2)
new_features = pca.fit_transform(X)  # Extracts top 2 features
new_features



array([[-0.43677621, -0.10308634],
       [ 0.57163439, -0.08274422],
       [ 0.60211987,  0.10543187],
       [-0.32000852, -0.28552751],
       [-0.41696953,  0.3659262 ]])

Q5. You are working on a project to build a recommendation system for a food delivery service. The dataset
contains features such as price, rating, and delivery time. Explain how you would use Min-Max scaling to
preprocess the data.

In [7]:
'''To normalize features price, rating, and delivery time for better comparison.
Apply Min-Max Scaling'''


import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Sample dataset with price, rating, and delivery time
food_data = np.array([
    [200, 4.5, 30],  # Price (₹), Rating, Delivery Time (mins)
    [150, 3.8, 40],
    [300, 4.9, 20],
    [100, 3.5, 50]
])

# Apply Min-Max Scaling
scaler = MinMaxScaler()
normalized_data = scaler.fit_transform(food_data)

print("Normalized Data:\n", normalized_data)



Normalized Data:
 [[0.5        0.71428571 0.33333333]
 [0.25       0.21428571 0.66666667]
 [1.         1.         0.        ]
 [0.         0.         1.        ]]


Q6. You are working on a project to build a model to predict stock prices. The dataset contains many
features, such as company financial data and market trends. Explain how you would use PCA to reduce the
dimensionality of the dataset.

In [9]:
'''Stock data has many features (financial trends, indicators).
Reduce to top principal components before training:'''
import numpy as np
from sklearn.decomposition import PCA

# Sample dataset: 10 stocks with 8 financial features each
stock_data = np.random.rand(10, 8)  # 10 samples (stocks), 8 features (indicators)

# Apply PCA to reduce to 5 principal components
pca = PCA(n_components=5)
reduced_stock_data = pca.fit_transform(stock_data)

print("Original Shape:", stock_data.shape)
print("Reduced Shape:", reduced_stock_data.shape)


Original Shape: (10, 8)
Reduced Shape: (10, 5)


Q7. For a dataset containing the following values: [1, 5, 10, 15, 20], perform Min-Max scaling to transform the
values to a range of -1 to 1

In [10]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

data = np.array([[1], [5], [10], [15], [20]])
scaler = MinMaxScaler(feature_range=(-1, 1))
scaled_data = scaler.fit_transform(data)
print(scaled_data)


[[-1.        ]
 [-0.57894737]
 [-0.05263158]
 [ 0.47368421]
 [ 1.        ]]
