Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)



Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [15]:
import numpy as np

# Original list of strings
list_ = ['1', '2', '3', '4', '5']

# Create a NumPy array from list_
array_list = np.array(object=list_)
print("Type of list_:", type(list_))
print("Type of array_list:", type(array_list))



Type of list_: <class 'list'>
Type of array_list: <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [16]:
print("Data types of elements in list_:")
for item in list_:
    print(item, "->", type(item))

print("\nData types of elements in array_list:")
for item in array_list:
    print(item, "->", type(item))


Data types of elements in list_:
1 -> <class 'str'>
2 -> <class 'str'>
3 -> <class 'str'>
4 -> <class 'str'>
5 -> <class 'str'>

Data types of elements in array_list:
1 -> <class 'numpy.str_'>
2 -> <class 'numpy.str_'>
3 -> <class 'numpy.str_'>
4 -> <class 'numpy.str_'>
5 -> <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [17]:
# Convert array_list to integers
array_list = np.array(object=list_, dtype=int)

print("Data types of elements in list_ (unchanged):")
for item in list_:
    print(item, "->", type(item))

print("\nData types of elements in array_list with dtype=int:")
for item in array_list:
    print(item, "->", type(item))


Data types of elements in list_ (unchanged):
1 -> <class 'str'>
2 -> <class 'str'>
3 -> <class 'str'>
4 -> <class 'str'>
5 -> <class 'str'>

Data types of elements in array_list with dtype=int:
1 -> <class 'numpy.int64'>
2 -> <class 'numpy.int64'>
3 -> <class 'numpy.int64'>
4 -> <class 'numpy.int64'>
5 -> <class 'numpy.int64'>


Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size


In [18]:
import numpy as np
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
print("Shape of num_array:", num_array.shape)  # Output: (2, 3)
print("Size of num_array:", num_array.size)      # Output: 6


Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [19]:
zeros_matrix = np.zeros((3, 3))
print("3x3 Matrix of zeros:")
print(zeros_matrix)


3x3 Matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [20]:
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
